In [20]:
import numpy as np

# Format

In [21]:
def input_matrix(n):
    matrix = []

    print(f"\nกรอก Matrix {n}x{n}")

    for i in range(n):
        row = list(map(float, input(f"แถวที่ {i+1}: ").split()))

        while len(row) != n:
            print(f"กรุณากรอก {n} ตัว")
            row = list(map(float, input(f"แถวที่ {i+1}: ").split()))

        matrix.append(row)

    return np.array(matrix)


# Eigenvalue

In [22]:
def find_eigenvalues(A):

    print("\n========== Eigenvalue ==========")

    eigenvalues = np.linalg.eigvals(A)

    for i, val in enumerate(eigenvalues):
        print(f"λ{i+1} =", round(val, 4))


# Eigenvector

In [23]:
def find_eigenvectors(A):

    print("\n========== Eigenvector ==========")

    eigenvalues, eigenvectors = np.linalg.eig(A)

    for i in range(len(eigenvalues)):

        print(f"\nEigenvalue λ{i+1} =", round(eigenvalues[i], 4))

        print("Eigenvector:")
        print(np.round(eigenvectors[:, i], 4))

# Diagonalizable

In [24]:
def diagonalize_matrix(A):

    print("\n========== Diagonalization ==========")

    eigenvalues, eigenvectors = np.linalg.eig(A)

    # rank = จำนวน eigenvector อิสระ
    rank = np.linalg.matrix_rank(eigenvectors)

    n = len(A)

    if rank == n:

        print("Matrix นี้สามารถแปลงเป็นเมทริกซ์ทแยงมุมได้")

        # P = eigenvector matrix
        P = eigenvectors

        # P inverse
        P_inv = np.linalg.inv(P)

        # D = P^-1 A P
        D = P_inv @ A @ P

        print("\nP =")
        print(np.round(P, 4))

        print("\nP^-1 =")
        print(np.round(P_inv, 4))

        print("\nD = P^-1 A P =")
        print(np.round(D, 4))

    else:

        print("Matrix นี้ไม่สามารถแปลงเป็นเมทริกซ์ทแยงมุมได้")
        print("เพราะมี Eigenvector อิสระไม่เพียงพอ")


# Main

In [25]:
print("===== Matrix Program =====")

# เลือกขนาด Matrix
size = int(input("เลือกขนาด Matrix (2 หรือ 3): "))

while size not in [2, 3]:
    size = int(input("กรุณาเลือกแค่ 2 หรือ 3: "))

# รับ Matrix
A = input_matrix(size)

print("\nMatrix A =")
print(A)

# Menu

while True:

    print("\n========== MENU ==========")
    print("1. หา Eigenvalue")
    print("2. หา Eigenvector")
    print("3. หา Diagonal Matrix")
    print("4. ออกโปรแกรม")

    choice = input("เลือกเมนู: ")

    if choice == "1":
        find_eigenvalues(A)

    elif choice == "2":
        find_eigenvectors(A)

    elif choice == "3":
        diagonalize_matrix(A)

    elif choice == "4":
        print("จบโปรแกรม")
        break

    else:
        print("เลือกใหม่")

===== Matrix Program =====

กรอก Matrix 2x2
กรุณากรอก 2 ตัว
กรุณากรอก 2 ตัว
กรุณากรอก 2 ตัว
กรุณากรอก 2 ตัว
กรุณากรอก 2 ตัว
กรุณากรอก 2 ตัว
กรุณากรอก 2 ตัว

Matrix A =
[[1. 2.]
 [1. 3.]]

========== MENU ==========
1. หา Eigenvalue
2. หา Eigenvector
3. หา Diagonal Matrix
4. ออกโปรแกรม

========== Diagonalization ==========
Matrix นี้สามารถแปลงเป็นเมทริกซ์ทแยงมุมได้

P =
[[-0.9391 -0.5907]
 [ 0.3437 -0.8069]]

P^-1 =
[[-0.8398  0.6148]
 [-0.3578 -0.9774]]

D = P^-1 A P =
[[0.2679 0.    ]
 [0.     3.7321]]

========== MENU ==========
1. หา Eigenvalue
2. หา Eigenvector
3. หา Diagonal Matrix
4. ออกโปรแกรม
จบโปรแกรม
